theme: jekyll-theme-architect
title: Suntimes
show_downloads: false
fdroid_link: https://f-droid.org/en/packages/com.forrestguice.suntimeswidget/
app_locales: 
 - en
 - ca
 - de
 - eo
 - es_ES
 - eu
 - fr
 - hu
 - it
 - nb
 - pl
 - pt_BR
 - zh_TW
plugins:
  - jekyll-seo-tag
