theme: jekyll-theme-architect
title: Suntimes
show_downloads: false
fdroid_link: https://f-droid.org/en/packages/com.forrestguice.suntimeswidget/
app_locales: 
 - en English
 - ca Catalan
 - de German
 - eo Esperanto
 - es_ES Spanish
 - eu Basque
 - fr French
 - hu Hungarian
 - it Italian
 - nb Norwegian
 - pl Polish
 - pt_BR Portuguese
 - zh_TW Chinese
app_versions:
 - v0.13.0
 - v0.13.0
app_versions1:
 - v0.3.1
plugins:
  - jekyll-seo-tag
